### ISSUE TITLE
Request to change to color theme of the website

### ISSUE THREAD

**Issue by tddschn** [victorlee/victorlee.github.io#3]
The current color scheme 2e2ec50 is not very appealing to human eyes.

Some components are not displayed clearly, for example [the forum](https://victorlee.github.io/forum):

![image](https://user-images.githubusercontent.com/45612704/95310188-adf11b00-08be-11eb-98cb-086366612d91.png)

Can you make it better? Thanks :)

**Comment by victorlee** [comment]
it is the same as your browser setting's default color, because uts color theme is set as 'preferred-color-scheme'.

**Comment by tddschn** [comment]
This is what it looks like in Google Chrome's incognito window:
![image](https://user-images.githubusercontent.com/45612704/95324387-3a590900-08d2-11eb-8e6e-ed20830dc213.png)

**Comment by victorlee** [comment]
@tddschn Yeah, is there a problem? I see nothing wrong

**Comment by tddschn** [comment]
- The borders of the comment boxes are not clear

**Comment by victorlee** [comment]
@tddschn I'm okay with it😂

**Comment by tddschn** [comment]
Ok that's fine😂
Never mind lol :)
